# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TRCAthenaV2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
      REACT_APP_TBA_API_KEY: ${{ secret.REACT_APP_TBA_API_KEY }}
      REACT_APP_NEXUS_API_KEY: ${{ secret.REACT_APP_NEXUS_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build with pnpm
        run: pnpm run build
        # Remove this step if your project does not require a build step.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09C0E85AF1F743AAAE0E321012D11BA7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CECEDE74EC604A6DBAEE40C96A81181C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2548ABA825094A798804AA469CD3B3B0 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TRCAthenaV2'
          slot-name: 'Production'
          package: .
          

