# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TRCAthenaV2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Generate package-lock.json from pnpm-lock.yaml for Azure compatibility
      - name: Generate package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating package-lock.json from pnpm-lock.yaml..."
            npm install --package-lock-only
          fi

      - name: Install dependencies with npm
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      # Clean up unnecessary files for deployment
      - name: Clean up for deployment
        run: |
          rm -rf node_modules/.cache
          rm -rf .next/cache

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCD6125CF06F4AD881A3689B7BB0E9AF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2CC0DBD42B84A74AB7ED9B75DC20F5C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DFB4759691274671B25F20B24595AAE3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TRCAthenaV2'
          slot-name: 'Production'
          package: .